#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-sphinx_gallery
Version  : 0.11.0
Release  : 7
URL      : https://files.pythonhosted.org/packages/13/6f/bc1c75c2e59bc676d1de23eba6f44b86261692997d4c036408ed546d3b13/sphinx-gallery-0.11.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/13/6f/bc1c75c2e59bc676d1de23eba6f44b86261692997d4c036408ed546d3b13/sphinx-gallery-0.11.0.tar.gz
Summary  : A Sphinx extension that builds an HTML version of any Python script and puts it into an examples gallery.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-sphinx_gallery-bin = %{version}-%{release}
Requires: pypi-sphinx_gallery-license = %{version}-%{release}
Requires: pypi-sphinx_gallery-python = %{version}-%{release}
Requires: pypi-sphinx_gallery-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(sphinx)

%description
==============
Sphinx-Gallery
==============
.. image:: https://dev.azure.com/sphinx-gallery/sphinx-gallery/_apis/build/status/sphinx-gallery.sphinx-gallery?branchName=master
:target: https://dev.azure.com/sphinx-gallery/sphinx-gallery/_build/latest?definitionId=1&branchName=master

%package bin
Summary: bin components for the pypi-sphinx_gallery package.
Group: Binaries
Requires: pypi-sphinx_gallery-license = %{version}-%{release}

%description bin
bin components for the pypi-sphinx_gallery package.


%package license
Summary: license components for the pypi-sphinx_gallery package.
Group: Default

%description license
license components for the pypi-sphinx_gallery package.


%package python
Summary: python components for the pypi-sphinx_gallery package.
Group: Default
Requires: pypi-sphinx_gallery-python3 = %{version}-%{release}

%description python
python components for the pypi-sphinx_gallery package.


%package python3
Summary: python3 components for the pypi-sphinx_gallery package.
Group: Default
Requires: python3-core
Provides: pypi(sphinx_gallery)
Requires: pypi(sphinx)

%description python3
python3 components for the pypi-sphinx_gallery package.


%prep
%setup -q -n sphinx-gallery-0.11.0
cd %{_builddir}/sphinx-gallery-0.11.0
pushd ..
cp -a sphinx-gallery-0.11.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1658942588
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-sphinx_gallery
cp %{_builddir}/sphinx-gallery-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sphinx_gallery/a5b31a24fffdc9afcf39f30c199a9fc95a08a427
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/copy_sphinxgallery.sh
/usr/bin/sphx_glr_python_to_jupyter.py

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-sphinx_gallery/a5b31a24fffdc9afcf39f30c199a9fc95a08a427

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
