#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-sphinx_gallery
Version  : 0.14.0
Release  : 19
URL      : https://files.pythonhosted.org/packages/eb/f8/a16a9f0680734d2e2a18324dffb8f34a43425794fc8b3e052013f6519bf5/sphinx-gallery-0.14.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/eb/f8/a16a9f0680734d2e2a18324dffb8f34a43425794fc8b3e052013f6519bf5/sphinx-gallery-0.14.0.tar.gz
Summary  : A `Sphinx <https://www.sphinx-doc.org/en/master/>`_ extension that builds an HTML gallery of examples from any set of Python scripts.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-sphinx_gallery-bin = %{version}-%{release}
Requires: pypi-sphinx_gallery-license = %{version}-%{release}
Requires: pypi-sphinx_gallery-python = %{version}-%{release}
Requires: pypi-sphinx_gallery-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(sphinx)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
==============
Sphinx-Gallery
==============
.. image:: https://img.shields.io/pypi/v/sphinx-gallery
:target: https://pypi.org/project/sphinx-gallery/
:alt: PyPI

%package bin
Summary: bin components for the pypi-sphinx_gallery package.
Group: Binaries
Requires: pypi-sphinx_gallery-license = %{version}-%{release}

%description bin
bin components for the pypi-sphinx_gallery package.


%package license
Summary: license components for the pypi-sphinx_gallery package.
Group: Default

%description license
license components for the pypi-sphinx_gallery package.


%package python
Summary: python components for the pypi-sphinx_gallery package.
Group: Default
Requires: pypi-sphinx_gallery-python3 = %{version}-%{release}

%description python
python components for the pypi-sphinx_gallery package.


%package python3
Summary: python3 components for the pypi-sphinx_gallery package.
Group: Default
Requires: python3-core
Provides: pypi(sphinx_gallery)
Requires: pypi(sphinx)

%description python3
python3 components for the pypi-sphinx_gallery package.


%prep
%setup -q -n sphinx-gallery-0.14.0
cd %{_builddir}/sphinx-gallery-0.14.0
pushd ..
cp -a sphinx-gallery-0.14.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1692381311
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-sphinx_gallery
cp %{_builddir}/sphinx-gallery-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sphinx_gallery/a5b31a24fffdc9afcf39f30c199a9fc95a08a427 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/copy_sphinxgallery.sh
/usr/bin/sphx_glr_python_to_jupyter.py

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-sphinx_gallery/a5b31a24fffdc9afcf39f30c199a9fc95a08a427

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
